# -*- coding: utf-8 -*-
"""iris_ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9OiOzgrsjK9i5SBS-rOC3xgQaJxt5NW

# Iris Machine Learning Project

## Abstract
This project uses the Iris dataset to build a simple machine learning model for classification.
We explore the data, train a Logistic Regression model, and visualize the results.

## Step 1: Import Libraries
All necessary Python libraries are imported, including pandas, numpy, scikit-learn, matplotlib, and seaborn.

## Step 2: Load and Explore Dataset
The Iris dataset is loaded from scikit-learn and converted to a pandas DataFrame.
Basic info, statistical summary, and target class counts are displayed.

## Step 3: Preprocess Data
The dataset is split into training and testing sets. Features are scaled using StandardScaler.

## Step 4: Train Model
Logistic Regression is used to train the model on the training set. Accuracy and classification report are printed.

## Step 5: Visualizations
Pairplots, class counts, and scatter plots show feature relationships and distribution of classes.

## Step 6: Conclusion
The model achieves around 93% accuracy, demonstrating that Logistic Regression can classify Iris flowers effectively.
"""

# Data manipulation
import pandas as pd
import numpy as np

# Machine Learning
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Load Iris dataset
iris = load_iris()

# Convert to pandas DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Check the first 5 rows
df.head()

# ===== Data Exploration =====

# Basic info about the dataset
print("Dataset Info:")
print(df.info())
print("\n")

# Statistical summary
print("Statistical Summary:")
print(df.describe())
print("\n")

# Count of each class in target
print("Target Value Counts:")
print(df['target'].value_counts())

# Pairplot to visualize feature relationships
sns.pairplot(df, hue='target', diag_kind='kde')
plt.show()

# ===== Step 3: Split the Dataset =====

# Features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# Split into train and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {X_train.shape[0]}, Testing samples: {X_test.shape[0]}")

# ===== Step 3.1: Scale Features =====
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Check first 5 rows of scaled features
pd.DataFrame(X_train_scaled, columns=X.columns).head()

# ===== Step 4: Train Logistic Regression Model =====

# Initialize the model
model = LogisticRegression(random_state=42, max_iter=200)

# Train the model
model.fit(X_train_scaled, y_train)

# Predict on test data
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on test data: {accuracy*100:.2f}%\n")

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# ===== Step 5: Visualizations =====

# 1️⃣ Pairplot colored by target
sns.pairplot(df, hue='target', diag_kind='kde')
plt.suptitle("Pairplot of Iris Features", y=1.02)
plt.show()

# 2️⃣ Count of each class
sns.countplot(x='target', data=df)
plt.title("Number of Samples per Iris Class")
plt.xticks(ticks=[0,1,2], labels=iris.target_names)
plt.show()

# 3️⃣ Scatter plot of first two features (for visualization)
plt.figure(figsize=(8,6))
for t, c, label in zip([0,1,2], ['red', 'green', 'blue'], iris.target_names):
    plt.scatter(
        X_test_scaled[y_test==t, 0],
        X_test_scaled[y_test==t, 1],
        c=c, label=label
    )
plt.xlabel(iris.feature_names[0] + " (scaled)")
plt.ylabel(iris.feature_names[1] + " (scaled)")
plt.title("Test Set Feature Scatter Plot")
plt.legend()
plt.show()